all: socket-simple-server socket-simple-client


socket-simple-server:
	gcc -g -O0 socket-simple-server.c -o socket-simple-server

socket-simple-client:
	gcc -g -O0 socket-simple-client.c -o socket-simple-client



.PHONY clear:
	rm -rf socket-simple-server socket-simple-client
